resources:
  - name: spring-music
    type: git
    source:
      uri: https://github.com/cloudfoundry-samples/spring-music.git
      branch: master

  - name: spring-music-k8s
    type: git
    source:
      uri: https://github.com/nthomson-pivotal/spring-music-k8s.git
      branch: master

  - name: spring-music-docker-image
    type: docker-image
    source:
      email: ((docker-hub-email))
      username: ((docker-hub-username))
      password: ((docker-hub-password))
      repository: ((docker-hub-username))/spring-music

jobs:
  - name: package
    plan:
    - get: spring-music
      trigger: true
    - task: package
      privileged: true
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: java, tag: openjdk-8}

        inputs:
          - name: spring-music

        outputs:
          - name: build-output
            path: spring-music/build/libs

        run:
          dir: "spring-music"
          path: "./gradlew"
          args: ["assemble"]

    - put: spring-music-docker-image
      params:
        build: spring-music-k8s
        build_args:
          JAR_FILE: build-output/spring-music-1.0.jar